server:
  port: 8085
feign:
  okhttp:
    enabled: true
sc:
  db:
    database: sc-pay
  swagger:
    title: StoreCloud商城支付服务接口文档
    description: StoreCloud商城支付服务接口文档
    package: com.storecloud.pay.controller