server:
  port: 8083
feign:
  okhttp:
    enabled: true
sc:
  db:
    database: sc-user
  swagger:
    title: StoreCloud商城用户服务接口文档
    description: StoreCloud商城用户服务接口文档
    package: com.storecloud.user.controller
  jwt:
    location: classpath:storecloud.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m